@startuml

    start --> [PreMainTasks]
	[PreMainTasks] -right-> [MainTask] : then
	[MainTask] -right-> [PostMainTasks] : then
	[PostMainTasks] --> [Links] : then

	[Links] --> [Reactions] : then

	[Reactions] -down-> [DECISION]  : then
	[DECISION] .right.> [Links] : not-done


	[DECISION] ..> [CALL_PARENT] : done
	[PreMainTasks] ..> [CALL_PARENT] : skip-main-task
	[PostMainTasks] ..> [CALL_PARENT] : skip-links

	[CALL_PARENT] ..> end
@enduml